### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by matthieu-perso** [semi-technologies/weaviate-on-gcp-marketplace#8]
Hey @etiennedi and @bobvanluijt,

I wanted to install weaviate on gcp via marketplace, but it is deprecated. Any suggested alternatives ?

**Comment by bobvanluijt** [comment]
Hi @MatthieuMoullecDev – this is correct, you can use the k8s setup as outlined [here](https://weaviate.io/developers/weaviate/current/getting-started/installation.html#kubernetes-k8s). In case of questions you can reach out to us on our public [Slack channel](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw).

PS:
We should make this repo private to avoid confusion @etiennedi

**Comment by matthieu-perso** [comment]
Thanks for the link and quick reply @bobvanluijt, exactly what I was looking for

**Comment by iSuslov** [comment]
@bobvanluijt @etiennedi hey guys, any plans on making this repository private? :)

**Comment by bobvanluijt** [comment]
That's a good idea ;)
